### ISSUE TITLE
There is ".ld.sh.swo"

### ISSUE THREAD

**Issue by coord-e** [Cj-bc/CommonToolsForTerminal#1]
There is ".ld.sh.swo" in "Forges".
Is it needed? I think it is temporary file.

**Comment by Cj-bc** [comment]
I don't know why there's it.
I didn't make...
But because I don't know the system well,I Tentatively　leave it here.
Do u know mean of ".swo" ?

**Comment by coord-e** [comment]
it's in "Forges".
You can't see it because the name of ".ld.sh.swo" is started from "."(dot)
To see it, you have to put "ls -a"

".swo" is one of "swap file".
It is made when vi is crashed.
Probably vi is crashed when you were editing "ld.sh".
if your "ld.sh" is ok, you can remove ".ld.sh.swo".
Let's do this 
"rm .ld.sh.swo"

**Comment by Cj-bc** [comment]
Yes,I see.
I've see it.
In short, the "swo" file is backup file,isn't it?
I see the mean now,So I remove it soon.
Thanks.

**Comment by coord-e** [comment]
Yes, It's backup.
